server:
  port: 8000
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: info
#    org.hibernate.type: trace
spring:
  devtools:
    livereload:
      enabled: true

  profiles:
    active: local

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  datasource:
    #    driver-class-name: org.h2.jdbcx.JdbcDataSource
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:ddareung2db;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1; #접속 URL
    username: admin
    password: admin
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      maximum-pool-size: 10
      minimumIdle: 9
      idleTimeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      maxLifetime: 30000
      #      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        cache:
          usesecondlevelcache: true
          usequerycache: false
          region:
            factoryclass: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
        generatestatistics: true

api:
  key:
    weather: 6QhJt2TrTftbPuSc98xTzMCNmpgtgKzi4bpewt0SFwMKQJdbMD8A4AIxH0XWd8%2FTypTiB%2ByVA0TD19qtj8wB4A%3D%3D
    station: 784e68756e73696c36334f5a426b4a
    airPollution: 6QhJt2TrTftbPuSc98xTzMCNmpgtgKzi4bpewt0SFwMKQJdbMD8A4AIxH0XWd8%2FTypTiB%2ByVA0TD19qtj8wB4A%3D%3D
